// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveRequest_Direction int32

const (
	MoveRequest_UP    MoveRequest_Direction = 0
	MoveRequest_RIGHT MoveRequest_Direction = 1
	MoveRequest_DOWN  MoveRequest_Direction = 2
	MoveRequest_LEFT  MoveRequest_Direction = 3
)

// Enum value maps for MoveRequest_Direction.
var (
	MoveRequest_Direction_name = map[int32]string{
		0: "UP",
		1: "RIGHT",
		2: "DOWN",
		3: "LEFT",
	}
	MoveRequest_Direction_value = map[string]int32{
		"UP":    0,
		"RIGHT": 1,
		"DOWN":  2,
		"LEFT":  3,
	}
)

func (x MoveRequest_Direction) Enum() *MoveRequest_Direction {
	p := new(MoveRequest_Direction)
	*p = x
	return p
}

func (x MoveRequest_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveRequest_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_game_game_proto_enumTypes[0].Descriptor()
}

func (MoveRequest_Direction) Type() protoreflect.EnumType {
	return &file_game_game_proto_enumTypes[0]
}

func (x MoveRequest_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveRequest_Direction.Descriptor instead.
func (MoveRequest_Direction) EnumDescriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{2, 0}
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction MoveRequest_Direction `protobuf:"varint,5,opt,name=direction,proto3,enum=game.MoveRequest_Direction" json:"direction,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *MoveRequest) GetDirection() MoveRequest_Direction {
	if x != nil {
		return x.Direction
	}
	return MoveRequest_UP
}

type StepFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S int64                  `protobuf:"varint,1,opt,name=s,proto3" json:"s,omitempty"`
	T *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=t,proto3" json:"t,omitempty"`
}

func (x *StepFrame) Reset() {
	*x = StepFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFrame) ProtoMessage() {}

func (x *StepFrame) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFrame.ProtoReflect.Descriptor instead.
func (*StepFrame) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *StepFrame) GetS() int64 {
	if x != nil {
		return x.S
	}
	return 0
}

func (x *StepFrame) GetT() *timestamppb.Timestamp {
	if x != nil {
		return x.T
	}
	return nil
}

type GameWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GameWorld) Reset() {
	*x = GameWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameWorld) ProtoMessage() {}

func (x *GameWorld) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameWorld.ProtoReflect.Descriptor instead.
func (*GameWorld) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameWorld) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Offset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dx float64 `protobuf:"fixed64,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy float64 `protobuf:"fixed64,2,opt,name=dy,proto3" json:"dy,omitempty"`
}

func (x *Offset) Reset() {
	*x = Offset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offset) ProtoMessage() {}

func (x *Offset) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offset.ProtoReflect.Descriptor instead.
func (*Offset) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{5}
}

func (x *Offset) GetDx() float64 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *Offset) GetDy() float64 {
	if x != nil {
		return x.Dy
	}
	return 0
}

type TankAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position          *Offset `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	BodyAngle         float32 `protobuf:"fixed32,2,opt,name=body_angle,json=bodyAngle,proto3" json:"body_angle,omitempty"`
	TurretAngle       float32 `protobuf:"fixed32,3,opt,name=turret_angle,json=turretAngle,proto3" json:"turret_angle,omitempty"`
	TargetBodyAngle   float32 `protobuf:"fixed32,4,opt,name=target_body_angle,json=targetBodyAngle,proto3" json:"target_body_angle,omitempty"`
	TargetTurretAngle float32 `protobuf:"fixed32,5,opt,name=target_turret_angle,json=targetTurretAngle,proto3" json:"target_turret_angle,omitempty"`
	Name              string  `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TankAttr) Reset() {
	*x = TankAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TankAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankAttr) ProtoMessage() {}

func (x *TankAttr) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankAttr.ProtoReflect.Descriptor instead.
func (*TankAttr) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{6}
}

func (x *TankAttr) GetPosition() *Offset {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *TankAttr) GetBodyAngle() float32 {
	if x != nil {
		return x.BodyAngle
	}
	return 0
}

func (x *TankAttr) GetTurretAngle() float32 {
	if x != nil {
		return x.TurretAngle
	}
	return 0
}

func (x *TankAttr) GetTargetBodyAngle() float32 {
	if x != nil {
		return x.TargetBodyAngle
	}
	return 0
}

func (x *TankAttr) GetTargetTurretAngle() float32 {
	if x != nil {
		return x.TargetTurretAngle
	}
	return 0
}

func (x *TankAttr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TanksAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tanks []*TankAttr `protobuf:"bytes,1,rep,name=tanks,proto3" json:"tanks,omitempty"`
	Step  *StepFrame  `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
}

func (x *TanksAttr) Reset() {
	*x = TanksAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TanksAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TanksAttr) ProtoMessage() {}

func (x *TanksAttr) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TanksAttr.ProtoReflect.Descriptor instead.
func (*TanksAttr) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{7}
}

func (x *TanksAttr) GetTanks() []*TankAttr {
	if x != nil {
		return x.Tanks
	}
	return nil
}

func (x *TanksAttr) GetStep() *StepFrame {
	if x != nil {
		return x.Step
	}
	return nil
}

var File_game_game_proto protoreflect.FileDescriptor

var file_game_game_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x7c, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a,
	0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10,
	0x03, 0x22, 0x43, 0x0a, 0x09, 0x53, 0x74, 0x65, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x73, 0x12, 0x28, 0x0a, 0x01,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x01, 0x74, 0x22, 0x1b, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x64, 0x78, 0x12, 0x0e, 0x0a,
	0x02, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x64, 0x79, 0x22, 0xe6, 0x01,
	0x0a, 0x08, 0x54, 0x61, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x41, 0x6e,
	0x67, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x75, 0x72, 0x72, 0x65, 0x74, 0x5f, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x75, 0x72, 0x72, 0x65,
	0x74, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x41, 0x6e, 0x67,
	0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x75, 0x72,
	0x72, 0x65, 0x74, 0x5f, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x75, 0x72, 0x72, 0x65, 0x74, 0x41, 0x6e, 0x67,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x56, 0x0a, 0x09, 0x54, 0x61, 0x6e, 0x6b, 0x73, 0x41,
	0x74, 0x74, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x74, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x6e, 0x6b, 0x41, 0x74,
	0x74, 0x72, 0x52, 0x05, 0x74, 0x61, 0x6e, 0x6b, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53,
	0x74, 0x65, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x32, 0xd3,
	0x01, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x43, 0x68, 0x61, 0x72, 0x12, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x30, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x43, 0x68, 0x61, 0x72, 0x12, 0x11, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22,
	0x00, 0x12, 0x30, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x61, 0x6e, 0x6b, 0x12, 0x0e,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x6e, 0x6b, 0x41, 0x74, 0x74, 0x72, 0x1a, 0x0f,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x6e, 0x6b, 0x73, 0x41, 0x74, 0x74, 0x72, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x2f, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x6e,
	0x6b, 0x12, 0x0e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x6e, 0x6b, 0x41, 0x74, 0x74,
	0x72, 0x1a, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x22, 0x00, 0x42, 0x3e, 0x0a, 0x0c, 0x69, 0x6e, 0x6b, 0x2e, 0x73, 0x66, 0x73, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x21, 0x73, 0x66, 0x73, 0x2e, 0x69, 0x6e, 0x6b, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x67,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_game_proto_rawDescOnce sync.Once
	file_game_game_proto_rawDescData = file_game_game_proto_rawDesc
)

func file_game_game_proto_rawDescGZIP() []byte {
	file_game_game_proto_rawDescOnce.Do(func() {
		file_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_game_proto_rawDescData)
	})
	return file_game_game_proto_rawDescData
}

var file_game_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_game_proto_goTypes = []interface{}{
	(MoveRequest_Direction)(0),    // 0: game.MoveRequest.Direction
	(*LoginRequest)(nil),          // 1: game.LoginRequest
	(*LoginResponse)(nil),         // 2: game.LoginResponse
	(*MoveRequest)(nil),           // 3: game.MoveRequest
	(*StepFrame)(nil),             // 4: game.StepFrame
	(*GameWorld)(nil),             // 5: game.GameWorld
	(*Offset)(nil),                // 6: game.Offset
	(*TankAttr)(nil),              // 7: game.TankAttr
	(*TanksAttr)(nil),             // 8: game.TanksAttr
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_game_game_proto_depIdxs = []int32{
	0, // 0: game.MoveRequest.direction:type_name -> game.MoveRequest.Direction
	9, // 1: game.StepFrame.t:type_name -> google.protobuf.Timestamp
	6, // 2: game.TankAttr.position:type_name -> game.Offset
	7, // 3: game.TanksAttr.tanks:type_name -> game.TankAttr
	4, // 4: game.TanksAttr.step:type_name -> game.StepFrame
	1, // 5: game.Game.LoginChar:input_type -> game.LoginRequest
	3, // 6: game.Game.MoveChar:input_type -> game.MoveRequest
	7, // 7: game.Game.RelayTank:input_type -> game.TankAttr
	7, // 8: game.Game.UpdateTank:input_type -> game.TankAttr
	2, // 9: game.Game.LoginChar:output_type -> game.LoginResponse
	4, // 10: game.Game.MoveChar:output_type -> game.StepFrame
	8, // 11: game.Game.RelayTank:output_type -> game.TanksAttr
	4, // 12: game.Game.UpdateTank:output_type -> game.StepFrame
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_game_game_proto_init() }
func file_game_game_proto_init() {
	if File_game_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TankAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TanksAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_game_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_game_proto_goTypes,
		DependencyIndexes: file_game_game_proto_depIdxs,
		EnumInfos:         file_game_game_proto_enumTypes,
		MessageInfos:      file_game_game_proto_msgTypes,
	}.Build()
	File_game_game_proto = out.File
	file_game_game_proto_rawDesc = nil
	file_game_game_proto_goTypes = nil
	file_game_game_proto_depIdxs = nil
}
